### ISSUE TITLE
MRTK3 Input Action asset mapping with the steamVR input

### ISSUE THREAD

**Issue by ghost** [VRStudios/Unity3D-XRInput#5]
So, here is my objective, I have a MRTK3 project and I am using MRTK3 rig in my scene. MRTK3 uses input action asset and various action maps and actions for interaction with its UI/UX or interactables. 
Any possible way that I can link inputs that you are able to get or SteamVR inputs to the MRTK input action asset or if thats not possible can I at least create my own input action asset based on the inputs that you are able to fetch. Can I make an input action asset in your solution project.
I am able to get the HMD pose and controllers pose in steamVR but I cant find a way to map the inputs to MRTK3 input action asset so that I can use MRTK3 resources with ease as at the center of MRTK3 interactions is the input action asset where they have mapped various actions to the various controller inputs. 
Sorry  for the long and complex query (I am using an OpenXR device)

**Comment by zezba9000** [comment]
I don't know much about MRTK3.
My guess is MRTK3 is directly grabbing Input from Unity's Input system instead of allowing you to feed it like it should have been designed. A lot of stuff in Unity3D is over-engineered tbh.

My guess is you will have to create your own Unity3D Input System module (which I've not done before). Then MRTK3 will probably pick up input from that.

For your specific need why can't you just use OpenXR in Unity3D running with SteamVR and Unity's Input System?
Are you specifically wanting XRInput to feed Unity's Input System data or something?

**Comment by ghost** [comment]
You are correct about - MRTK3 directly grabbing Input from Unity's Input system. It is doing it using Input action assets. 
What you suggested i.e. "use OpenXR in Unity3D running with SteamVR and Unity's Input System" should ideally work for me but as per my knowledge, SteamVR has only given openXR support for the pose of hmd and controllers and insists that for input we will have to use the steam vr input system only (Had read this in one of their issues threads).
Where I am stuck is that - I have an input action asset with some actions mapped in it. These actions are referred everywhere in my project. I somehow want to link the SteamVR input/XRInput to the unity's input action asset system.

**Comment by zezba9000** [comment]
If you have a custom Unity Input action system you should be able to grab XRInput data and feed it to your stuff.
You can force XRInput to use OpenVR input library if thats what you're hoping for. However I'm not sure if this conflicts with OpenXR input system (as normally you use one or the other and the internal SteamVR runtime may only support one at a time).

**Comment by VRDave** [comment]
SteamVR actually has full controller support in OpenXR. You should be able to use the Unity Input System and associated bindings. The biggest thing to remember is to add your Controller Profiles for each build target in Project Settings > XR Plug-in Management > OpenXR. 

Since MRTK3 is built on top of Unity’s XR Interaction Toolkit, you can actually get some default input action maps if you import the Starter Assets sample package in Package Manager. If you are new to the complexities of the Input System, it can help acclimate you to what it expects.

**Comment by ghost** [comment]
@zezba9000 @VRDave Thank you for your guidance. I was using both OpenVR XR plugin and OpenXR plugin earlier. So it was conflicting with each other. I ended up removing entire steamVR and related stuff from the project and just kept openXR. Also as dave suggested, I had to add the necessary profile in the openXR section, without it nothing works. Also make sure that you have latest SteamVR installed which has OpenXR support included.
I just found it sad that steamVR has not made a documentation about unity set up in order to work with OpenXR smoothly. Or maybe I didnt find one.

**Comment by zezba9000** [comment]
> I just found it sad that steamVR has not made a documentation about unity set up in order to work with OpenXR smoothly. Or maybe I didnt find one.

I wouldn't expect 3rd parties to document Unity3D. While some do its normally only for special case situations.
Glad you figured it out.
